### ISSUE TITLE
[C++ serialisation] Where are nunavut::support::SerializeResult and nunavut::support::bitspan defined?

### ISSUE THREAD

**Issue by aentinger** [OpenCyphal/nunavut#264]
The headers were generated using
```bash
$ nnvg --version
1.9.0
```
and with the following commands:
```bash
nnvg --experimental-languages \
     --target-language cpp \
     --pp-max-emptylines=1  \
     --pp-trim-trailing-whitespace \
     --target-endianness=any \
     --enable-serialization-asserts \
     --outdir public_regulated_data_types/uavcan-header \
     public_regulated_data_types/uavcan
```
```bash
nnvg --experimental-languages \
     --target-language cpp \
     --pp-max-emptylines=1  \
     --pp-trim-trailing-whitespace \
     --target-endianness=any \
     --enable-serialization-asserts \
     --lookup public_regulated_data_types/uavcan \
     --outdir public_regulated_data_types/reg-header \
     public_regulated_data_types/reg
```
However, I was unable to locate the definition of `nunavut::support::SerializeResult` and `nunavut::support::bitspan` which are basically used in every single compiled DSDL type? I did not find them in nunavut/support/* (and nowhere else in the generated files).

**Comment by ASMfreaK** [comment]
Please, rerun your commands with `--generate-support always` flags. This should generate `nunavut/support/serialization.hpp`.
Both `nunavut::support::SerializeResult` and `nunavut::support::bitspan` are defined there.

**Comment by ASMfreaK** [comment]
This is strange, though. For some reason, support folders (`nunavut/support`) were created, but not files. As far as I can see, the files were needed, but not generated. 

I think it is a bug, but I don't know `nunavut`'s python implementation in detail, so maybe @thirtytwobits can say for sure.

**Comment by thirtytwobits** [comment]
Sorry for the late reply. I'll look into this...

**Comment by thirtytwobits** [comment]
I can't reproduce this problem on mac. What environment are you using?

**Comment by thirtytwobits** [comment]
Please re-open if you are still seeing this with V2
