### ISSUE TITLE
C++: Fixed length boolean arrays should be represented as std::bitset

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/nunavut#283]
cc @thirtytwobits @ASMfreaK 

This is critical because without this optimization, `uavcan.port.List` cannot be used in small embedded systems. See https://nunaweb.opencyphal.org/api/storage/docs/docs/uavcan/index.html#uavcan_node_port_SubjectIDList_0_1

**Comment by pavel-kirienko** [comment]
Looking at the current implementation, I assume this will require an extension of the configuration parameter set unless we want to hard-code std::bitset for booleans.

**Comment by thirtytwobits** [comment]
This should be fixed with 2.0.7
