### ISSUE TITLE
The local testing insturctions are obsolete

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/nunavut#288]
Aren't we supposed to be using ghcr instead of dockerhub?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/3298404/222776629-38d80434-c121-43bd-bec5-2defc50c96a1.png">

If it was possible to make these instructions less prone to obsolescence, that would be helpful.

**Comment by thirtytwobits** [comment]
This should be fixed with 2.0.7
