### ISSUE TITLE
Clang:  Add support for clang compiler 

### ISSUE THREAD

**Issue by hab-0** [OpenCyphal/nunavut#299]
The current generated files (c++) are not compatible with the Clang compiler https://clang.llvm.org/.
e.g:
The following syntax used on the Nunavut generated files is not supported by the Clang compiler:
[[deprecated( string-literal )]]

**Comment by thirtytwobits** [comment]
Sorry @hab-0 , but can you provide the version of clang you are using? We do compile using clang c++14 as part of our CI so it is generally compatible.
