### ISSUE TITLE
Test against Windows

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/nunavut#60]
[Certain projects](https://pyuavcan.readthedocs.io/) that depend on this fine library (not nnvg) are going to support Windows soon. My preliminary assessment indicates that the library is at least generally functional with no obvious issues.

This might be relevant: https://github.com/UAVCAN/pydsdl/pull/28

**Comment by thirtytwobits** [comment]
Making progress. Almost have it working.

**Comment by thirtytwobits** [comment]
Fixed!
